feat(rollout)!: Rollout Schedulers
ecmwf/anemoi-core pull request #46
Opened 2024-12-20 11:02 UTC by HCookie

Closes https://github.com/ecmwf/anemoi-core/issues/14

# Rollout Schedulers

Expand the ways to describe rollout, and provide an interface to schedule updates
## New default rollout config
```yaml
# length of the "rollout" window (see Keisler's paper)
rollout:
  _target_: anemoi.training.schedulers.stepped.EpochStepped
  minimum: 1
  maximum: 12
  # increase rollout every n epochs
  every_n_epochs: 1
  # Control the incrementing of the rollout window
  increment:
    step:
      0: 0
      200000: 1 # After 200k steps, increment by 1 every 1 epoch
```
Can step by epoch, step, and control the increment based on either the step or epoch.

Additonally, formally add random steppers.
## Todo

- [ ] Integrate with the data loader
- [ ] Ensure that the randomness is seeded appropriately and broadcast
- [ ] Ensure restartability and ability to change config

2025-01-07 10:25 UTC, anaprietonem reviewed
Started to go through the PR and left some comments! I still need to understand better some of the functionality so hope te questions makes sense. Thanks for this Harrison!

2025-01-07 10:25 UTC, anaprietonem commented on training/src/anemoi/training/train/train.py
> +            reload_dataloaders_every_n_epochs=self._need_to_reload_dataloaders,
Is there a reason why the type of `reload_dataloaders_every_n_epochs` has been changes from `int` to `bool`? Wondering because looking at PTL docs the type of flag is `int` (https://lightning.ai/docs/pytorch/stable/_modules/lightning/pytorch/trainer/trainer.html#Trainer.__init__) and that's used by the `[data_connector](https://github.com/Lightning-AI/pytorch-lightning/blob/master/src/lightning/pytorch/trainer/connectors/data_connector.py#L51)`

2025-01-07 10:25 UTC, anaprietonem commented on training/src/anemoi/training/diagnostics/callbacks/rollout.py
> +    def on_validation_epoch_end(self, trainer: pl.Trainer, pl_module: pl.LightningModule, *_) -> None:
If someone sets the limit_batches for validation to 0, to skip validation this hook wouldn't be triggered?

2025-01-07 10:25 UTC, anaprietonem commented on training/src/anemoi/training/train/forecaster.py
> +        self.rollout: RolloutScheduler = instantiate(config.training.rollout)
Nice, looks much cleaner!

2025-01-07 10:25 UTC, anaprietonem commented on training/src/anemoi/training/train/forecaster.py
> +        for rollout_step in range(rollout or int(self.rollout)):
Do we still need to pass rollout as a value to this function is you are already making it a self variable of the `GraphForecaster` ?

2025-01-07 10:25 UTC, anaprietonem commented on training/src/anemoi/training/train/forecaster.py
> +        # Cannot use stepping due to inconsistent behaviour with Pytorch Lightning
Just to understand it better, what do you mean here with the inconsistent behaviour with PTL?

2025-01-07 10:25 UTC, anaprietonem commented on training/src/anemoi/training/train/forecaster.py
> +    def on_load_checkpoint(self, checkpoint: dict) -> None:
In the docs for the `Modelhooks` I can't find a hook for `on_load_checkpoint` https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.core.hooks.ModelHooks.html#lightning.pytorch.core.hooks.ModelHooks so maybe I am missing something but how is this working?

2025-01-09 08:11 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-core?pullRequest=46) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-core?pullRequest=46) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/anemoi-core?pullRequest=46) it.</sub>

2025-01-09 10:30 UTC, HCookie commented on training/src/anemoi/training/train/train.py
> +            reload_dataloaders_every_n_epochs=self._need_to_reload_dataloaders,
Due to python duck typing I suppose a `True` will evaluate to `1` when used as an int. So it works, but if it is clearer, I can change it to an int.

2025-01-09 10:31 UTC, HCookie commented on training/src/anemoi/training/diagnostics/callbacks/rollout.py
> +    def on_validation_epoch_end(self, trainer: pl.Trainer, pl_module: pl.LightningModule, *_) -> None:
Good point, I'll need to take a look.

2025-01-09 10:32 UTC, HCookie commented on training/src/anemoi/training/train/forecaster.py
> +        for rollout_step in range(rollout or int(self.rollout)):
Passing it as an arg allows for override, which I think is used in some of the callbacks.

2025-01-09 10:32 UTC, HCookie commented on training/src/anemoi/training/train/forecaster.py
> +        # Cannot use stepping due to inconsistent behaviour with Pytorch Lightning
If I use the step function, it gets triggered in sanity checking, and other places where I don't want it,

2025-01-09 10:33 UTC, HCookie commented on training/src/anemoi/training/train/forecaster.py
> +    def on_load_checkpoint(self, checkpoint: dict) -> None:
https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.core.hooks.CheckpointHooks.html
It seems to be here?

2025-01-10 07:51 UTC, anaprietonem commented on training/src/anemoi/training/config/training/default.yaml
> +      200000: 1 # After 200k steps, increment by 1 every 1 epoch
I am probably just being slow but how does this interacts with the `limit batches`?  What would be the difference between doing the above, and the 'old configuration' with a limit batches of  200000?

2025-01-10 07:52 UTC, anaprietonem commented on training/tests/schedulers/__init__.py
> +# (C) Copyright 2024 Anemoi contributors.
Minor thing, but just a remainder that all of these headers would need to be updated to 2025 before merging

2025-01-10 07:55 UTC, anaprietonem commented on training/src/anemoi/training/train/train.py
> +            reload_dataloaders_every_n_epochs=self._need_to_reload_dataloaders,
I see now, thanks for the clarification! all good then

2025-01-10 08:02 UTC, anaprietonem commented on training/src/anemoi/training/train/train.py
> +    def _need_to_reload_dataloaders(self) -> bool:
Have you seen any difference in terms of runtime from using this?

2025-01-10 08:16 UTC, anaprietonem commented on training/src/anemoi/training/train/forecaster.py
> +    def on_load_checkpoint(self, checkpoint: dict) -> None:
Nice yep you're right, I did not know about that! so all good

2025-01-10 09:02 UTC, HCookie commented on training/src/anemoi/training/train/train.py
> +    def _need_to_reload_dataloaders(self) -> bool:
Unfortunately, yes, I need to still quantify it, but it does slow down the transition between epochs.

2025-01-10 09:03 UTC, HCookie commented on training/src/anemoi/training/config/training/default.yaml
> +      200000: 1 # After 200k steps, increment by 1 every 1 epoch
The `limit_batches` ends the training, this will continue on, and then begin updating the rollout.

2025-01-10 09:05 UTC, HCookie commented on training/tests/schedulers/__init__.py
> +# (C) Copyright 2024 Anemoi contributors.
Even the code I wrote in 2024? I honestly have no idea

2025-01-30 09:41 UTC, HCookie commented on training/src/anemoi/training/schedulers/rollout/randomise.py
> +        return self._dist_rollout[0]
@cathalobrien Can you verify this does what I think it does?

2025-01-30 10:02 UTC, cathalobrien commented on training/src/anemoi/training/schedulers/rollout/randomise.py
> +        return self._dist_rollout[0]
Looks good! Each process picks a value and stores it in `_dist_rollout`. Then, if you have more then 1 process, the global rank zero process overwrites everyone elses value with its copy. 

You have the `try...except ValueError` in case torch.dist is not initalised I guess? You could try replace with

```python
if dist.is_initialized() and dist.get_world_size() > 1:
   dist.broadcast(self._dist_rollout, src=0)
```
Maybe the world_size check is not needed, I would hope a broadcast with a single member would just complete straight away.

One question I have here, should the rollout value be constant across and within all models? I don't know enough about rollout. But here you dont pass a model_comm_group to broadcast so that's what you'd get.

2025-01-30 11:30 UTC, HCookie commented on training/src/anemoi/training/schedulers/rollout/randomise.py
> +        return self._dist_rollout[0]
Good point about the constant value across all models, 
What would I need for the model_comm_group to be used here?

2025-01-30 11:31 UTC, HCookie commented on training/src/anemoi/training/schedulers/rollout/randomise.py
> +            pass
```suggestion
        if dist.is_initialized() and dist.get_world_size() > 1:
                dist.broadcast(self._dist_rollout, src=0)
```

2025-01-30 11:54 UTC, cathalobrien commented on training/src/anemoi/training/schedulers/rollout/randomise.py
> +        return self._dist_rollout[0]
Your call to broadcast would change slightly, and you'd have to pass model_comm_group into the function somehow
```python
- dist.broadcast(self._dist_rollout, src=0)
+ dist.broadcast(self._dist_rollout, group=model_comm_group, group_src=0)
```
Then each process within a `model_comm_group` would get the same rollout value. Each `model_comm_group` could have a different value

2025-01-31 15:44 UTC, sahahner commented
This PR is great. Thank you for that! I have invented a few scheduling protocols and most of them work. There are a few edge cases that we might want to support
- The scheduler allows negative steps, which is useful in the case when the user wants to decrease the number of rollout steps. Nevertheless, the actual rollout should never be negative, we would be going in the wrong direction with our forecast. This should be easy to fix by comparing to the minimum rollout provided how we also limit by the maximum rollout provided.
- At the moment, when the counter reaches the maximum rollout step it is still increased internally. I think this should not be the case in order to allow decreasing this number again after some number of epochs/steps.

2025-01-31 17:31 UTC, HCookie commented
@sahahner Addressed in [c132ed9](https://github.com/ecmwf/anemoi-core/pull/46/commits/c132ed9c24b330d9aed7b00e64921139031c84ea)

2025-02-03 13:20 UTC, sahahner commented on training/docs/user-guide/training.rst
> +   rollout:
Should the specifications for training.rollout be indented?

2025-02-03 13:32 UTC, sahahner commented on training/src/anemoi/training/train/forecaster.py
> +        loss *= 1.0 / int(self.rollout)
I see `int(self.rollout)` twice in the `_step` function. Does it make sense to ensure that self.rollout is always an int?

2025-02-03 14:23 UTC, HCookie commented on training/src/anemoi/training/train/forecaster.py
> +        loss *= 1.0 / int(self.rollout)
So that is can be used as for the divide it needs to be cast to an int.
If I add rdiv to the class it will work without the cast.

2025-02-03 14:27 UTC, HCookie commented on training/docs/user-guide/training.rst
> +   rollout:
Probably....

2025-02-04 10:22 UTC, sahahner commented on training/src/anemoi/training/schedulers/schedulers.py
> +from typing_extensions import Self
This is not working for all supported python versions.

2025-02-04 12:39 UTC, sahahner commented on training/src/anemoi/training/train/forecaster.py
> +    def on_train_epoch_end(self, *_) -> None:
Can we add the new rollout step to these logger outputs?

2025-02-04 14:49 UTC, HCookie commented on training/src/anemoi/training/train/forecaster.py
> +    def on_train_epoch_end(self, *_) -> None:
As in log the rollout when stepped?

2025-02-04 14:54 UTC, sahahner commented on training/src/anemoi/training/train/forecaster.py
> +    def on_train_epoch_end(self, *_) -> None:
I mean adding the rollout to these logging statements:
`LOGGER.debug("Stepping Rollout on train epoch end")`

2025-02-04 14:54 UTC, sahahner commented on training/src/anemoi/training/train/forecaster.py
> +    def on_train_epoch_end(self, *_) -> None:
I don't think logging all changes to rollout step in the info terminal output is necessary as the rollout is tracked as a model metric.

2025-02-04 15:02 UTC, HCookie commented on training/src/anemoi/training/train/forecaster.py
> +    def on_train_epoch_end(self, *_) -> None:
Resolved in cc060b0db307537ba83ed50fb0d4cab4a0252d79

2025-02-04 15:37 UTC, sahahner commented on training/src/anemoi/training/train/forecaster.py
> +    def on_train_epoch_end(self, *_) -> None:
Should the print come after the update of the rollout step? LOGGER.info needs some string formatting.
```suggestion
    def on_train_epoch_end(self, *_) -> None:
        if self.trainer.limit_val_batches == 0:
            self.rollout.step_epoch()
            LOGGER.info("Stepping Rollout on train epoch end, rollout: %i", int(self.rollout))

    def on_validation_epoch_end(self, *_) -> None:
        if not self.trainer.sanity_checking:
            self.rollout.step_epoch()
            LOGGER.info("Stepping Rollout on validation epoch end, rollout: %i", int(self.rollout))
```

2025-02-04 17:53 UTC, HCookie commented on training/src/anemoi/training/train/forecaster.py
> +    def on_train_epoch_end(self, *_) -> None:
Fixed

2025-02-18 16:04 UTC, ssmmnn11 requested changes
nice, please see comments

2025-02-18 16:04 UTC, ssmmnn11 commented on training/src/anemoi/training/train/train.py
> +    def _need_to_reload_dataloaders(self) -> bool:
this will clash with the data loader seeding -> we get a base seed at the beginning of the training run. can you check that the runs are still shuffled differently for every epoch? otherwise we need to increment the random seed according to e.g. epoch

2025-02-18 16:04 UTC, ssmmnn11 commented on training/src/anemoi/training/schedulers/rollout/__init__.py
> +        step: int | None = None,
Does this work now with restaring?

So when my job get canceld at rollout  = 3, and I am halfway through the dataloader, does the module now when I restart that it only needs to do 1/2 of the dataloader, and skip the rest before incrementing the rollout again?

2025-02-18 16:16 UTC, HCookie commented on training/src/anemoi/training/schedulers/rollout/__init__.py
> +        step: int | None = None,
As the rollout is calculated as a product of step and epoch, restarting works just fine from the rollout's perspective. The step and epoch are stored in the last checkpoint, and only incremented when appropriate. Regarding the dataloader part that is out of scope of this one, and will require work on that class.

2025-02-18 17:15 UTC, HCookie commented
@ssmmnn11 
> can you check that the runs are still shuffled differently for every epoch?

They are not, the indices are the same for each epoch. 
However, I have been thinking further on the need to reload, I think it may be possible to do it without it, but I'll need to figure out how to broadcast a value to all the dataloader workers, as this is why they do not update. Rebuilding them obviously fixed that but causes other issues.

2025-02-19 08:13 UTC, ssmmnn11 commented
persistent_workers=False means we have an initial seed and then just draw randon numbers from the generator, hence there should not be any repetition. 

What we could do: before we did not have the epoch information in the dataset. This should now be the case and you could simply add the epoch to the random seed:

https://github.com/ecmwf/anemoi-core/blob/83d72e17b5c8017a1d9a47f75e0848e0bbb080a3/training/src/anemoi/training/data/dataset.py#L224

something like: base_seed = get_base_seed() + self.epoch * 100

though we should probably rename base_seed here to dataset_seed otherwise it might be confusing -> we call refer to the base seed elsewhere in the code.

2025-02-19 13:56 UTC, HCookie commented on training/src/anemoi/training/train/train.py
> +    def _need_to_reload_dataloaders(self) -> bool:
Fixed it in upcoming commit hopefully

2025-03-12 10:27 UTC, merged