Models feature/normalization layers
ecmwf/anemoi-core pull request #47
Opened 2024-12-20 11:49 UTC by jakob-schloer

### Describe your changes

This PR makes it possible to switch the implementation of Linear and LayerNorm kernels in the config.

At the moment we use torch.NN implementation for many layers in Anemoi model e.g. torch.nn.layerNorm, torch.NN.linear. This has the advantage of being available out of the box with torch and portable to many systems (CPU, AMD and Nvidia GPUs). However, other layer implementations might be more efficient for certain hardware, or we might want to use a custom layer.

This PR adds the following block to config/model/.yaml:
```
  layer_kernels:
    LayerNorm:
      #_target_: "transformer_engine.pytorch.LayerNorm"
      _target_: "liger_kernel.transformers.rms_norm.LigerRMSNorm"
      #_target_: "torch.nn.LayerNorm" #the default PyTorch implementation
      _partial_: True
      #Any arguments to your chosen function go here e.g.
      #bias: False
    Linear:
      #_target_: "transformer_engine.pytorch.Linear"
      _target_: "torch.nn.Linear"
      _partial_: True
```

You can pass any parameters to your new kernels in the config file, after "partial : True". Hydra tries to load the desired kernel in "models/encoder_processor_decoder.py". If the desired library isn't available, torch currently will fall back to torch.nn..

The calls to torch.nn are then replaced with

```
- self.layer_norm = nn.LayerNorm(normalized_shape=num_channels)
+ self.layer_norm = layer_kernels['LayerNorm'](normalized_shape=num_channels)
```

In the future, this syntax could be extended to replace other layers if required. More specifically, a follow up PR that includes conditional layer norm.

### Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

### Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation and docstrings to reflect the changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have ensured that the code is still pip-installable after the changes and runs
- [ ] I have not introduced new dependencies in the inference partion of the model
- [ ] I have ran this on single GPU
- [ ] I have ran this on multi-GPU or multi-node
- [ ] I have ran this to work on LUMI (or made sure the changes work independently.)
- [ ] I have ran the Benchmark Profiler against the old version of the code

2025-01-08 13:35 UTC, ssmmnn11 requested changes
great work!

2025-01-08 13:35 UTC, ssmmnn11 commented on models/src/anemoi/models/layers/block.py
> +        # Why does the GraphTransformer not have a layer_norm_mlp like the Transformer?
it is part of the mlp iirc

2025-01-08 13:35 UTC, ssmmnn11 commented on models/src/anemoi/models/layers/block.py
> +        self.layer_norm_attention_2 = layer_kernels["LayerNorm"](normalized_shape=in_channels)
I don't like the naming layer_norm_attention and layer_norm_attention_2

maybe layer_norm_attention_src and layer_norm_attention_dst ?

2025-01-08 13:35 UTC, ssmmnn11 commented on models/src/anemoi/models/layers/block.py
> +        )  # Why does this use layer_norm_attention_2? And only is a mapper thing?
we can remove this comment. we have two layernorms here, because we  are doing cross attention and normalise the src and dst nodes.

2025-01-08 13:35 UTC, ssmmnn11 commented on models/src/anemoi/models/layers/chunk.py
> +        layer_norm: Optional[dict] = None,
layer_kernels?

2025-01-08 13:35 UTC, ssmmnn11 commented on models/src/anemoi/models/layers/normalization.py
> +        self.norm = nn.LayerNorm(normalized_shape, elementwise_affine=False)  # no learnable parameters
I guess this one is a bit more complex, because here we would like to be able to configure the layer kernel inside of the layernorm ... can you think about a way how to do this? maybe overkill for this first implementation.

2025-01-08 13:35 UTC, ssmmnn11 commented on training/src/anemoi/training/config/model/gnn.yaml
> +      _target_: torch.nn.LayerNorm #the default PyTorch implementation
the gnn should run with the autocast layernorm, otherwise the memory requirements will be large.

2025-01-08 16:34 UTC, jakob-schloer commented on models/src/anemoi/models/layers/normalization.py
> +        self.norm = nn.LayerNorm(normalized_shape, elementwise_affine=False)  # no learnable parameters
I thought we might define custom normalization layers in the `normalization.py` which we would then specify in the config, e.g. 
```
layer_kernels:
    LayerNorm:
      _target_: anemoi.models.layers.normalization.AutocastLayerNorm
      _partial_: True
```

How would you want to use the AutocastLayerNorm?

2025-01-08 16:38 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-core?pullRequest=47) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/anemoi-core?pullRequest=47) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: jakob-schloer<br/>:x: cathalobrien<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/anemoi-core?pullRequest=47) it.</sub>

2025-01-08 16:46 UTC, ssmmnn11 commented on models/src/anemoi/models/layers/normalization.py
> +        self.norm = nn.LayerNorm(normalized_shape, elementwise_affine=False)  # no learnable parameters
What I mean is that we might want to use conditional layernorms, but with e.g. a rms norm from liger instead of the pytorch implementation. 

A first workaround would be of course to have multiple conditional layernorms, but with different layernorm implementations. This can also be a future iteration and does not have to be implemented here.

2025-01-08 16:52 UTC, jakob-schloer commented on models/src/anemoi/models/layers/normalization.py
> +        self.norm = nn.LayerNorm(normalized_shape, elementwise_affine=False)  # no learnable parameters
I was discussing this with @cathalobrien but we couldn't think of an easy way to do that yet. I would probably do that at a later stage.

2025-01-08 17:02 UTC, ssmmnn11 requested changes
One last thing :-)

2025-01-08 17:02 UTC, ssmmnn11 commented on training/src/anemoi/training/config/model/gnn.yaml
> +      _target_: anemoi.models.layers.normalization.AutocastLayerNorm #the default PyTorch implementation
can you remove #the default ...

2025-01-09 08:04 UTC, jakob-schloer commented on training/src/anemoi/training/config/model/gnn.yaml
> +      _target_: anemoi.models.layers.normalization.AutocastLayerNorm #the default PyTorch implementation
Done

2025-01-09 09:30 UTC, ssmmnn11 approved these changes
looks good!

2025-01-24 08:55 UTC, merged